import express from 'express';
import { register, login, getProfile, updateProfile, logout, changePassword, createRecoveryCode, recoverAccount } from '../controllers/auth.controller.js';
import { protect } from '../middleware/auth.js';
import { rateLimit, userKey } from '../middleware/limits.js';
const router = express.Router();
const attempts = rateLimit('auth-ip', 20, 15 * 60000);
const identity = rateLimit('auth-identity', 10, 15 * 60000, req => typeof req.body?.email === 'string' ? req.body.email.trim().toLowerCase().slice(0, 254) : req.ip);
router.post('/register', attempts, identity, register);
router.post('/login', attempts, identity, login);
router.post('/recover', attempts, identity, recoverAccount);
router.post('/recovery-code', protect, rateLimit('recovery-user', 5, 900000, userKey), createRecoveryCode);
router.get('/profile', protect, getProfile);
router.put('/profile', protect, updateProfile);
router.post('/logout', protect, logout);
router.put('/password', protect, rateLimit('password', 5, 15 * 60000, req => req.user._id), changePassword);
export default router;
